### ISSUE TITLE
[bug] Right clicking isopropyl alchohol (untextured) crashes game

### ISSUE THREAD

**Issue by HigherLight** [blueminecraftteam/healthmod-fabric#3]
**Before creating an issue**
- [ ] Is the bug caused by another mod? don't know
- [ ] Is the bug a vanilla issue? no
- [ ] Has the bug already been filed? no
- [ ] Are you using an outdated version (of minecraft, mod or mod loader)? no

**Describe the bug**
When you hold the isopropyl alchohol in your hand and right click with it, it will crash the game.

**To Reproduce**
1. Run mod
2. Right click isopropyl alchohol
3. Crash

**Expected behavior**
no crash

**Screenshots**
no

**Information**

Minecraft version: 1.16.4
Mod version: 1.0.0-alpha.1
Mod loader: Fabric
Mod loader version: 0.10.8

**Additional context**
no

**Comment by xf8b** [comment]
where log
