### ISSUE TITLE
[bug] Right clicking isopropyl alchohol crashes game

### ISSUE THREAD

**Issue by HigherLight** [blueminecraftteam/healthmod-fabric#4]
**Before creating an issue**

- [ ] Is the bug caused by another mod?
- [ ] Is the bug a vanilla issue?
- [ ] Has the bug already been filed?
- [ ] Are you using an outdated version (of minecraft, mod or mod loader)?

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Information**

Minecraft version: 1.16.4
Mod version: 1.0.0 alpha 1
Mod loader: Fabric
Mod loader version: 1.16.4 v.0.10.8

**Additional context**

**Comment by xf8b** [comment]
duplicate of #3
